# 版本号
[versions]
common_base = "1.0.0"

io_base = "1.0.0"

storage_file = "1.0.0"

serial_basecode = "1.0.0"
serial_gson = "1.0.0"

math_base = "1.0.0"

finance_base = "1.0.0"

security_digest = "1.0.0"


# ----- 插件 -----
repo_public = "1.0.0"
repo_private = "1.0.0"
publish_private = "1.0.0"


# 组件
[libraries]
common_base = { group = "net.bi4vmr.tool.java", name = "common-base", version.ref = "common_base" }

io_base = { group = "net.bi4vmr.tool.java", name = "io-base", version.ref = "io_base" }

storage_file = { group = "net.bi4vmr.tool.java", name = "storage-file", version.ref = "storage_file" }

serial_basecode = { group = "net.bi4vmr.tool.java", name = "serialization-basecode", version.ref = "serial_basecode" }
serial_gson = { group = "net.bi4vmr.tool.java", name = "serialization-gson", version.ref = "serial_gson" }

math_base = { group = "net.bi4vmr.tool.java", name = "math-base", version.ref = "math_base" }

finance_base = { group = "net.bi4vmr.tool.java", name = "finance-base", version.ref = "finance_base" }

security_digest = { group = "net.bi4vmr.tool.java", name = "security-digest", version.ref = "security_digest" }


# Gradle插件
[plugins]
# ----- Java -----
# Maven公开仓库
repo_public = { id = "net.bi4vmr.gradle.plugin.repo.public", version.ref = "repo_public" }
# Maven私有仓库
repo_private = { id = "net.bi4vmr.gradle.plugin.repo.private", version.ref = "repo_private" }
# Maven Publish私有仓库配置
publish_private = { id = "net.bi4vmr.gradle.plugin.maven.publish", version.ref = "publish_private" }
